- hosts: security_jenkins_webserver_dmz
  become: true
  tasks:
  - name: Removing previous code
    file:
      path: /var/www/html/website
      state: absent
  - git:
      repo: https://github.com/giridharuniverse21/giripress.git
      dest: /var/www/html/website
